name: Newman run

on:
  push:
    branches:
      - main
      
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: Create dir for report
        run: |
          mkdir testArtifacts

      - name: Install Newm
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
      - name: Run test
        run: newman run ServeRest.postman_collection.json -e ServerRest_env.postman_environment.json -r cli,htmlextra
        
      - name: Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Reports
          path: newman
